web:
  build: ./web
  command: python -u run.py
  ports:
    - '5000:5000'
  volumes:
    - ./web:/app/web
  links:
    - database
database:
  image: mongo:3.6
  volumes:
    - ./database/data:/data/db
