version: '3'

services:
  web:
    build: ./web
    command: python -u run.py
    volumes:
      - ./web:/app/web
    depends_on:
      - db

  db:
    image: mongo:3.6
    volumes:
      - ./data:/data/db
