version: '2'

services:
  web:
    build: ./web
    command: python -u run.py
    restart: always
    ports:
      - '80:5000'
    volumes:
      - ./web:/app/web
    depends_on:
      - db

  db:
    image: mongo:3.6
    volumes:
      - ./data:/data/db
