version: '2'

services:
  app:
    build: .
    command: python -u undepress/run.py
    restart: always
    ports:
      - '80:5000'
    env_file:
      - ./undepress/.env
    volumes:
      - ./undepress:/app/undepress
    depends_on:
      - db

  db:
    image: mongo:3.6
    volumes:
      - undepress_db:/data/db

volumes:
  undepress_db:
