version: '3'

services:
  web:
    restart: always
    build: ./web
    ports:
      - '5000:5000'
    volumes:
      - ./web/src:/app/web/src
    links:
      - db
  db:
    image: mongo:3.6
    ports:
      - '27017:27017'
    volumes:
      - ./db/data:/data/db
